export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const GET_ALL_ORGANIZATIONS = "GET_ALL_ORGANIZATIONS";
export const MARK_INTERESTED = "MARK_INTERESTED";
export const MARK_NOT_INTERESTED = "MARK_NOT_INTERESTED";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
export const EDIT_ORGANIZATION = "EDIT_ORGANIZATION";
export const APPROVE_ORGANIZATION = "APPROVE_ORGANIZATION";
