export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const GET_ALL_ORGANIZATIONS = "GET_ALL_ORGANIZATIONS";
export const MARK_INTERESTED = "MARK_INTERESTED";
export const MARK_NOT_INTERESTED = "MARK_NOT_INTERESTED";